x="hello world"
print(x)
i=29
print(i)
f=20.26
print(f)
i=26
a=85
print(i+a)
x=1j
print(x)
x=["apple","banana","cherry"]
print(x)
x=("apple","banana","cherry")
print(x)
x={"name":"johan","age":36}
print(x)
x={"apple","banana","cherry"}
print(x)
x=range(6)
print(x)
x=True
print(x)
x=bytearray(5)
print(x)
x=frozenset({"apple","banana","cherry"})
print(x)
x=b"tirtha"
print(x)
x=memoryview(bytes(5))
print(x)